### ISSUE TITLE
Digest mails stopped sending out

### ISSUE THREAD

**Issue by turboladen** [turboladen/hub_hub#87]
No one is getting digest emails anymore.

Looks like the cron job is triggering (from the cron log):

```
May  3 23:15:01 chat crond[25712]: (deploy) CMD (/bin/bash -l -c 'cd /var/www/chat.mindhub.org/releases/20130501065010 && script/rails runner -e production '\''DigestMailer.nightly_email_everyone'\''')
```

I see this in the production log file:

```
Connecting to database specified by database.yml
Connecting to database specified by database.yml
Starting nightly email to digest users...
Sending digest mail to admin@mindhub.org...
  Rendered digest_mailer/nightly_email.html.haml within layouts/email_poster (79.8ms)
  Rendered layouts/_footer.html.haml (5.9ms)
  Rendered digest_mailer/nightly_email.text.haml (6.8ms)
```

The method that sends out the email does this:

```
    logger.info 'Done sending nightly email to digest users.'
```

...but that doesn't show in the log file anywhere.

The `maillog` shows:

```
May  3 23:16:55 chat sendmail[25970]: r446Gsjr025970: from=deploy, size=10768, class=0, nrcpts=1, msgid=<201305040616.r446Gsjr025970@chat.mindhub.org>, relay=deploy@localhost
May  3 23:16:57 chat postfix/smtpd[25973]: connect from localhost[127.0.0.1]
May  3 23:16:57 chat postfix/smtpd[25973]: 76A8224038: client=localhost[127.0.0.1]
May  3 23:16:57 chat postfix/cleanup[25975]: 76A8224038: message-id=<201305040616.r446Gsjr025970@chat.mindhub.org>
May  3 23:16:57 chat sendmail[25970]: r446Gsjr025970: to=deploy, ctladdr=deploy (502/502), delay=00:00:03, xdelay=00:00:02, mailer=relay, pri=40768, relay=[127.0.0.1] [127.0.0.1], dsn=2.0.0, stat=Sent (Ok: queued as 76A8224038)
May  3 23:16:57 chat postfix/smtpd[25973]: disconnect from localhost[127.0.0.1]
May  3 23:16:58 chat postfix/qmgr[21519]: 76A8224038: from=<deploy@chat.mindhub.org>, size=11345, nrcpt=1 (queue active)
May  3 23:16:58 chat postfix/local[25976]: 76A8224038: to=<deploy@chat.mindhub.org>, relay=local, delay=1.3, delays=0.74/0.5/0/0.07, dsn=2.0.0, status=sent (delivered to mailbox)
May  3 23:16:58 chat postfix/qmgr[21519]: 76A8224038: removed
```

...but nothing else until 5 hours later, which doesn't look related.

**Comment by turboladen** [comment]
If I run the job manually, I actually get a backtrace (not sure why this doesn't get logged!)

```
/var/www/chat.mindhub.org/releases/20130507002608/app/assets/stylesheets/email.css.scss:2: File to import not found or unreadable: bootstrap/_variables. (Sass::SyntaxError)
Load path: /var/www/chat.mindhub.org/releases/20130507002608
  (in /var/www/chat.mindhub.org/releases/20130507002608/app/assets/stylesheets/email.css.scss)
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/import_node.rb:67:in `rescue in import'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/import_node.rb:45:in `import'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/import_node.rb:28:in `imported_file'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/import_node.rb:37:in `css_import?'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/perform.rb:217:in `visit_import'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/base.rb:37:in `visit'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/perform.rb:100:in `visit'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/base.rb:53:in `map'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/base.rb:53:in `visit_children'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/base.rb:37:in `block in visit'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/perform.rb:128:in `visit_root'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/base.rb:37:in `visit'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/perform.rb:100:in `visit'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/perform.rb:7:in `visit'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/root_node.rb:20:in `render'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/engine.rb:315:in `_render'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/engine.rb:262:in `render'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/tilt-1.3.7/lib/tilt/css.rb:24:in `evaluate'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/tilt-1.3.7/lib/tilt/template.rb:77:in `render'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/context.rb:193:in `block in evaluate'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/context.rb:190:in `each'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/context.rb:190:in `evaluate'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/processed_asset.rb:12:in `initialize'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:249:in `new'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:249:in `block in build_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:270:in `circular_call_protection'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:248:in `build_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:93:in `block in build_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/caching.rb:19:in `cache_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:92:in `build_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:169:in `find_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:60:in `find_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/bundled_asset.rb:16:in `initialize'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:252:in `new'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:252:in `build_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:93:in `block in build_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/caching.rb:19:in `cache_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:92:in `build_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:169:in `find_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:60:in `find_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/css_loaders.rb:22:in `load'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/css_helper.rb:36:in `block in load_css'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/css_helper.rb:35:in `each'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/css_helper.rb:35:in `load_css'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/css_helper.rb:21:in `block in css_for_doc'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/css_helper.rb:21:in `map'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/css_helper.rb:21:in `css_for_doc'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/customized_premailer.rb:15:in `initialize'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/hook.rb:71:in `new'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/hook.rb:71:in `premailer'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/hook.rb:61:in `generate_html_part'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/hook.rb:38:in `generate_html_part_replacement'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/hook.rb:16:in `perform'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/hook.rb:7:in `delivering_email'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/mail-2.5.3/lib/mail/mail.rb:230:in `block in inform_interceptors'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/mail-2.5.3/lib/mail/mail.rb:229:in `each'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/mail-2.5.3/lib/mail/mail.rb:229:in `inform_interceptors'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/mail-2.5.3/lib/mail/message.rb:217:in `inform_interceptors'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/mail-2.5.3/lib/mail/message.rb:227:in `deliver'
    from /var/www/chat.mindhub.org/releases/20130507002608/app/mailers/digest_mailer.rb:36:in `nightly_email'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/base.rb:167:in `process_action'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/base.rb:121:in `process'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/rendering.rb:45:in `process'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/actionmailer-3.2.13/lib/action_mailer/base.rb:459:in `process'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/actionmailer-3.2.13/lib/action_mailer/base.rb:453:in `initialize'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/actionmailer-3.2.13/lib/action_mailer/base.rb:439:in `new'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/actionmailer-3.2.13/lib/action_mailer/base.rb:439:in `method_missing'
    from /var/www/chat.mindhub.org/releases/20130507002608/app/mailers/digest_mailer.rb:16:in `block in nightly_email_everyone'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/relation/delegation.rb:6:in `each'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/relation/delegation.rb:6:in `each'
    from /var/www/chat.mindhub.org/releases/20130507002608/app/mailers/digest_mailer.rb:15:in `nightly_email_everyone'
    from (eval):1:in `<top (required)>'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/commands/runner.rb:53:in `eval'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/commands/runner.rb:53:in `<top (required)>'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/commands.rb:64:in `require'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/commands.rb:64:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by turboladen** [comment]
Worked for the first night, now is failing again:

```
/var/www/chat.mindhub.org/releases/20130507235313/app/assets/stylesheets/email.css.scss:2: File to import not found or unreadable: bootstrap. (Sass::SyntaxError)
Load path: /var/www/chat.mindhub.org/releases/20130507235313
  (in /var/www/chat.mindhub.org/releases/20130507235313/app/assets/stylesheets/email.css.scss)
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/import_node.rb:67:in `rescue in import'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/import_node.rb:45:in `import'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/import_node.rb:28:in `imported_file'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/import_node.rb:37:in `css_import?'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/perform.rb:217:in `visit_import'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/base.rb:37:in `visit'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/perform.rb:100:in `visit'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/base.rb:53:in `map'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/base.rb:53:in `visit_children'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/base.rb:37:in `block in visit'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/perform.rb:128:in `visit_root'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/base.rb:37:in `visit'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/perform.rb:100:in `visit'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/visitors/perform.rb:7:in `visit'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/tree/root_node.rb:20:in `render'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/engine.rb:315:in `_render'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sass-3.2.8/lib/sass/engine.rb:262:in `render'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/tilt-1.3.7/lib/tilt/css.rb:24:in `evaluate'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/tilt-1.3.7/lib/tilt/template.rb:77:in `render'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/context.rb:193:in `block in evaluate'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/context.rb:190:in `each'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/context.rb:190:in `evaluate'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/processed_asset.rb:12:in `initialize'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:249:in `new'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:249:in `block in build_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:270:in `circular_call_protection'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:248:in `build_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:93:in `block in build_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/caching.rb:19:in `cache_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:92:in `build_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:169:in `find_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:60:in `find_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/bundled_asset.rb:16:in `initialize'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:252:in `new'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:252:in `build_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:93:in `block in build_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/caching.rb:19:in `cache_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:92:in `build_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/base.rb:169:in `find_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/sprockets-2.2.2/lib/sprockets/index.rb:60:in `find_asset'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/css_loaders.rb:22:in `load'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/css_helper.rb:36:in `block in load_css'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/css_helper.rb:35:in `each'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/css_helper.rb:35:in `load_css'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/css_helper.rb:21:in `block in css_for_doc'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/css_helper.rb:21:in `map'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/css_helper.rb:21:in `css_for_doc'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/customized_premailer.rb:15:in `initialize'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/hook.rb:71:in `new'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/hook.rb:71:in `premailer'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/hook.rb:61:in `generate_html_part'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/hook.rb:38:in `generate_html_part_replacement'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/hook.rb:16:in `perform'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/premailer-rails-1.4.0/lib/premailer/rails/hook.rb:7:in `delivering_email'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/mail-2.5.3/lib/mail/mail.rb:230:in `block in inform_interceptors'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/mail-2.5.3/lib/mail/mail.rb:229:in `each'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/mail-2.5.3/lib/mail/mail.rb:229:in `inform_interceptors'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/mail-2.5.3/lib/mail/message.rb:217:in `inform_interceptors'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/mail-2.5.3/lib/mail/message.rb:227:in `deliver'
    from /var/www/chat.mindhub.org/releases/20130507235313/app/mailers/digest_mailer.rb:36:in `nightly_email'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/base.rb:167:in `process_action'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/base.rb:121:in `process'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.13/lib/abstract_controller/rendering.rb:45:in `process'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/actionmailer-3.2.13/lib/action_mailer/base.rb:459:in `process'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/actionmailer-3.2.13/lib/action_mailer/base.rb:453:in `initialize'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/actionmailer-3.2.13/lib/action_mailer/base.rb:439:in `new'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/actionmailer-3.2.13/lib/action_mailer/base.rb:439:in `method_missing'
    from /var/www/chat.mindhub.org/releases/20130507235313/app/mailers/digest_mailer.rb:16:in `block in nightly_email_everyone'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/relation/delegation.rb:6:in `each'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/activerecord-3.2.13/lib/active_record/relation/delegation.rb:6:in `each'
    from /var/www/chat.mindhub.org/releases/20130507235313/app/mailers/digest_mailer.rb:15:in `nightly_email_everyone'
    from (eval):1:in `<top (required)>'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/commands/runner.rb:53:in `eval'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/commands/runner.rb:53:in `<top (required)>'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/commands.rb:64:in `require'
    from /var/www/chat.mindhub.org/shared/bundle/ruby/2.0.0/gems/railties-3.2.13/lib/rails/commands.rb:64:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by turboladen** [comment]
Manually triggering the digest mailer seems to be working now... we'll see about nightlies...
