### ISSUE TITLE
Set up user for posting from the old list server

### ISSUE THREAD

**Issue by turboladen** [turboladen/hub_hub#90]

**Comment by turboladen** [comment]
Doesn't look like emails are getting posted.

**Comment by turboladen** [comment]
Looks like a permissions problem; also effects the "admin" alias.

```
<list-recipient@chat.mindhub.org>: Command died with status 1: "
   RAILS_ENV=production /var/www/chat.mindhub.org/current/script/rails runner
   'PostMailer.receive(STDIN.read)'". Command output:
   /usr/local/rbenv/versions/2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in
   `require': cannot load such file -- bundler/setup (LoadError)  from
   /usr/local/rbenv/versions/2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in
   `require'  from /var/www/chat.mindhub.org/current/config/boot.rb:6:in `<top
   (required)>'  from
   /usr/local/rbenv/versions/2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in
   `require'  from
   /usr/local/rbenv/versions/2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in
   `require'  from /var/www/chat.mindhub.org/current/script/rails:5:in
   `<main>'
Reporting-MTA: dns; chat.mindhub.org
X-Postfix-Queue-ID: 63FCA24002
X-Postfix-Sender: rfc822; robert@inreachtech.net
Arrival-Date: Thu,  9 May 2013 12:00:14 -0700 (PDT)

Final-Recipient: rfc822; list-recipient@chat.mindhub.org
Original-Recipient: rfc822;list-recipient@chat.mindhub.org
Action: failed
Status: 5.3.0
Diagnostic-Code: x-unix;
   /usr/local/rbenv/versions/2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in
   `require': cannot load such file -- bundler/setup (LoadError)  from
   /usr/local/rbenv/versions/2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in
   `require'  from /var/www/chat.mindhub.org/current/config/boot.rb:6:in `<top
   (required)>'  from
   /usr/local/rbenv/versions/2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in
   `require'  from
   /usr/local/rbenv/versions/2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in
   `require'  from /var/www/chat.mindhub.org/current/script/rails:5:in
   `<main>'
```
